version: "3.9"  # optional since v1.27.0
services:
  bitsy-vault:
    image: ralston3/bitsy:vault-latest
    environment:
      - ENV=prod
    env_file: ./../../env/.env.prod
    ports:
      - "8002:8002"
    volumes:
      - .:/usr/local/bitsy-vault
      - logvolume01:/var/log
  bitsy-py:
    image: ralston3/bitsy:py-latest
    env_file: ./../../env/.env.prod
    environment:
      - ENV=prod
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_PASSWORD=${PG_PASSWORD}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/bitsy-py
      - logvolume01:/var/log
  bitsy-rs:
    image: ralston3/bitsy:rs-latest
    environment:
      - ENV=prod
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_PASSWORD=${PG_PASSWORD}
      - HOST=0.0.0.0
      - PORT=8080
    env_file: ./../../env/.env.prod
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/local/bitsy-rs
      - logvolume01:/var/log
volumes:
  logvolume01: {}
