version: "3.9"  # optional since v1.27.0
services:
  bitsy-api:
    image: bitsy/py:latest
    environment:
      - ENV=dev
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local
      - logvolume01:/var/log
  bitsy-vault:
    image: bitsy/vault:latest
    environment:
      - ENV=dev
    env_file: ./../env/.env.dev
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/local
      - logvolume01:/var/log
  bitsy-rs:
    image: bitsy/rs:latest
    environment:
      - ENV=dev
    env_file: ./../env/.env.dev
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/local
      - logvolume01:/var/log
volumes:
  logvolume01: {}
